language: rust
os:
    - linux
env:
    global:
        - secure: S+u/k4KrKTrzmC2pIg1WTilTFfKeymSR6jjsqbX+KQZ845WpY8o+PvQ6b9hNXMSRP1lKpFHSSLBjD5uNsK+2LI/3nI/siu4lJ8zBgy3VIrBRnBvruTBqSRlhQui5BgmMw9YaHldZBelR315TVDHfkwvjqivfjwQiOl7HfLIvaBM=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
